resources:
- name: sandbox-git
  type: git
  icon: github-circle
  source:
    uri: https://github.com/DaiYamask/sandbox

jobs:
- name: job
  public: true
  plan:
  - get: sandbox-git
    trigger: true
  - task: list-files
    config:
      inputs:
      - name: sandbox-git
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: ls
        args: ["-la", "./sandbox-git"]