resources:
- name: larvel-wesockets-git
  type: git
  icon: github-box
  source:
    uri: https://github.com/beyondcode/laravel-websockets.git

jobs:
- name: test
  public: true
  plan:
  - get: larvel-wesockets-git
    trigger: true
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: php, tag: 7.2-cli }
      inputs:
        - name: larvel-websockets-git
      run:
        path: /bin/sh
        args:
          - -c
          - |
            apt-get update
            apt-get install -7 git unzip

            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php --filename=composer --install-dir=/usr/bin
            php -r "unlink('composer-setup.php');"

            cd larvel-websocket-git

            composer install
            vendor/bin/phpunit --coverage-text --coverage